Cleans up the structure for the web app related docs
anoma/specs pull request #103
Opened 2022-06-09 11:15 UTC by memasdeligeorgakis

This solves https://github.com/anoma/specs/issues/102

2022-06-09 11:23 UTC, memasdeligeorgakis commented
I see strange rendering at the end of a few pages, such as here: `/architecture/clients/web-wallet/client-application.html`. @tzemanovic or @jurevans do you know what could cause this?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2773320/172835556-a835c24c-9c53-4b92-ac3e-43a866a67f1c.png">

2022-06-09 11:24 UTC, tzemanovic commented on src/SUMMARY.md
> +    - [Transparent Transactions](./architecture/clients/web-wallet/transparent-transactions.md)
let's organize it like this to follow the dir structure
```suggestion
    - [Web Wallet UI](./architecture/clients/web-wallet.md)
      - [IBC](./architecture/clients/web-wallet/ibc.md) 
      - [Client Application](./architecture/clients/web-wallet/client-application.md) 
      - [Key Derivation](./architecture/clients/web-wallet/key-derivation.md) 
      - [Persistence](./architecture/clients/web-wallet/persistence.md) 
      - [RPC](./architecture/clients/web-wallet/rpc.md) 
      - [Transparent Transactions](./architecture/clients/web-wallet/transparent-transactions.md)
    - [Explorer UI and Features](./architecture/clients/web-explorer-interface.md)
```

2022-06-09 11:41 UTC, tzemanovic commented
> I see strange rendering at the end of a few pages, such as here: `/architecture/clients/web-wallet/client-application.html`. @tzemanovic or @jurevans do you know what could cause this?
> 
> <img alt="image" width="785" src="https://user-images.githubusercontent.com/2773320/172835556-a835c24c-9c53-4b92-ac3e-43a866a67f1c.png">

yeah, it's katex plugin, see #91

2022-06-09 14:48 UTC, jurevans commented
> 

@tzemanovic I see the same thing in other docs (we haven't intended to use any Katex formatting). Thanks for catching that!

2022-06-09 15:49 UTC, tzemanovic requested changes
there are some dead links found in the CI:

``` 
error: File not found: ../architecture/clients/web-wallet-interface.md
   ┌─ releases/v1.md:80:3
   │
80 │ - [Web-based wallet](../architecture/clients/web-wallet-interface.md)
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: ../architecture/clients/web-wallet-interface.md
error: File not found: ../architecture/clients/web-explorer-interface.md
   ┌─ releases/v1.md:81:3
   │
81 │ - [Web-based block explorer](../architecture/clients/web-explorer-interface.md)
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File not found: ../architecture/clients/web-explorer-interface.md
```

2022-06-10 16:51 UTC, tzemanovic approved these changes
LGTM, thanks!

2022-06-10 16:52 UTC, merged