Governance spec update
anoma/specs pull request #89
Opened 2022-04-29 12:29 UTC by grarco

- Fixes typos
- Updates vote storage key

2022-05-02 12:58 UTC, cwgoes requested changes
Thanks, just one clarifying question

2022-05-02 12:58 UTC, cwgoes commented on src/architecture/governance/signaling.md
> +If a delegator votes accordingly to its validator, unless the transaction is being forced, the vote will not actually be submitted to the chain, as a small form of space optimization.
but what if the delegator votes prior to the 2/3 mark, where the validator could still change their vote? 

(or is this rendered impossible somehow?)

2022-05-02 13:17 UTC, Fraccaman commented on src/architecture/governance/signaling.md
> +If a delegator votes accordingly to its validator, unless the transaction is being forced, the vote will not actually be submitted to the chain, as a small form of space optimization.
yes, you are right. Without using the `--force` option the result depends if the validator voted or not. Still, delegators have the last 1/3 of the voting period to re-submit their vote. Do you think we should always send the votes?

2022-05-02 13:22 UTC, Fraccaman commented on src/architecture/governance/signaling.md
> +If a delegator votes accordingly to its validator, unless the transaction is being forced, the vote will not actually be submitted to the chain, as a small form of space optimization.
@grarco is suggesting that we could use the *optimized behaviour* only if delegators are submit a vote transaction during the ending 1/3 voting period

2022-05-03 09:08 UTC, cwgoes commented on src/architecture/governance/signaling.md
> +If a delegator votes accordingly to its validator, unless the transaction is being forced, the vote will not actually be submitted to the chain, as a small form of space optimization.
I agree with that suggestion. Default to safe :)

2022-05-03 15:10 UTC, grarco commented on src/architecture/governance/signaling.md
> +If a delegator votes accordingly to its validator, unless the transaction is being forced, the vote will not actually be submitted to the chain, as a small form of space optimization.
Specs updated to clarify this scenario

2022-05-03 16:44 UTC, Fraccaman commented
LGTM!

2022-05-03 16:44 UTC, Fraccaman approved these changes

2022-05-04 14:31 UTC, cwgoes approved these changes

2022-05-04 14:31 UTC, cwgoes commented
Thank you!

2022-05-04 14:31 UTC, merged